version: '3.9'

services:
  # Master 1
  mysql-master-1:
    image: mysql:8.0
    container_name: mysql-master-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: master1db
      MYSQL_USER: master
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql-master1-data:/var/lib/mysql
      - ./init-scripts/master1-init.sql:/docker-entrypoint-initdb.d/master1-init.sql
    command: --server-id=1 --log-bin=mysql-bin
    networks:
      - mysql_net

  # Slave 1
  mysql-slave-1:
    image: mysql:8.0
    container_name: mysql-slave-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_REPLICATION_USER: repluser
      MYSQL_REPLICATION_PASSWORD: 1234
      MYSQL_DATABASE: master1db
    ports:
      - "3317:3306"
    depends_on:
      - mysql-master-1
    volumes:
      - mysql-slave1-data:/var/lib/mysql
      - ./init-scripts/slave1-init.sql:/docker-entrypoint-initdb.d/slave1-init.sql
    command: --server-id=2
    networks:
      - mysql_net

  # Master 2
  mysql-master-2:
    image: mysql:8.0
    container_name: mysql-master-2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: master2db
      MYSQL_USER: master
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mysql-master2-data:/var/lib/mysql
      - ./init-scripts/master2-init.sql:/docker-entrypoint-initdb.d/master2-init.sql
    command: --server-id=3 --log-bin=mysql-bin
    networks:
      - mysql_net

  # Slave 2
  mysql-slave-2:
    image: mysql:8.0
    container_name: mysql-slave-2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_REPLICATION_USER: repluser
      MYSQL_REPLICATION_PASSWORD: 1234
      MYSQL_DATABASE: master2db
    ports:
      - "3318:3306"
    depends_on:
      - mysql-master-2
    volumes:
      - mysql-slave2-data:/var/lib/mysql
      - ./init-scripts/slave2-init.sql:/docker-entrypoint-initdb.d/slave2-init.sql
    command: --server-id=4
    networks:
      - mysql_net

networks:
  mysql_net:
    driver: bridge

volumes:
  mysql-master1-data:
  mysql-slave1-data:
  mysql-master2-data:
  mysql-slave2-data:
